"""Generate a narrow Codex profile for EDA Runtime work."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

DEFAULT_KEEP_NAMES = frozenset(
    {
        "eda-runtime-control",
        "ads-agent-bridge",
        "ads-kb-docs",
        "ansysem-agent-bridge",
        "ansysem-kb-docs",
    }
)
_NAME = re.compile(r"^name:\s*[\"']?([^\"'\r\n]+)", re.MULTILINE)


def discover_skills(codex_home: Path) -> list[tuple[Path, str]]:
    roots = [codex_home / "skills", codex_home / "plugins" / "cache"]
    found: list[tuple[Path, str]] = []
    for root in roots:
        if not root.is_dir():
            continue
        for skill_file in root.rglob("SKILL.md"):
            relative = skill_file.relative_to(root)
            if any(part.startswith(".") for part in relative.parts):
                continue
            try:
                header = skill_file.read_text(encoding="utf-8")[:4096]
            except (OSError, UnicodeError):
                continue
            match = _NAME.search(header)
            if match:
                found.append((skill_file.resolve(), match.group(1).strip()))
    return sorted(set(found), key=lambda item: str(item[0]).casefold())


def render_profile(
    skills: list[tuple[Path, str]],
    keep_names: set[str],
    *,
    runtime_command: str = "eda-runtime",
    approve_mutations: bool = False,
) -> str:
    lines = [
        "# Generated by EDA Bridge Runtime. Regenerate instead of editing path entries.",
        'approval_policy = "never"',
        'sandbox_mode = "read-only"',
        'model_reasoning_effort = "medium"',
        "",
        "[features]",
        "plugins = false",
        "apps = false",
        "browser_use = false",
        "computer_use = false",
        "image_generation = false",
        "memories = false",
        "multi_agent = false",
        "goals = false",
        "skill_search = false",
        "workspace_dependencies = false",
        "shell_snapshot = false",
        "",
        '[mcp_servers."eda-bridge-runtime"]',
        f"command = {json.dumps(runtime_command)}",
        'args = ["mcp", "serve"]',
        "required = true",
        'enabled_tools = ["eda.connections.list", "eda.connection.reset", '
        '"eda.context.resolve", "eda.capabilities", "eda.read", "eda.submit", '
        '"eda.run_plan", "eda.job.status", "eda.job.wait", "eda.job.events"]',
        "",
        "[[hooks.PreToolUse]]",
        'matcher = "^mcp__eda_bridge_runtime__.*$"',
        "",
        "[[hooks.PreToolUse.hooks]]",
        'type = "command"',
        'command = "eda-runtime hook codex-pre-tool-use"',
        "timeout = 3",
        "",
        "[[hooks.PostToolUse]]",
        'matcher = "^mcp__eda_bridge_runtime__.*$"',
        "",
        "[[hooks.PostToolUse.hooks]]",
        'type = "command"',
        'command = "eda-runtime hook codex-post-tool-use"',
        "timeout = 3",
        "",
    ]
    if approve_mutations:
        lines.extend(
            [
                '[mcp_servers."eda-bridge-runtime".tools."eda.submit"]',
                'approval_mode = "approve"',
                "",
                '[mcp_servers."eda-bridge-runtime".tools."eda.run_plan"]',
                'approval_mode = "approve"',
                "",
            ]
        )
    for path, name in skills:
        lines.extend(
            [
                "[[skills.config]]",
                f"path = {json.dumps(str(path))}",
                f"enabled = {'true' if name in keep_names else 'false'}",
                "",
            ]
        )
    return "\n".join(lines)


def install_profile(
    codex_home: Path,
    *,
    profile_name: str = "eda-runtime",
    keep_names: set[str] | None = None,
    runtime_command: str = "eda-runtime",
    approve_mutations: bool = False,
) -> tuple[Path, int, int]:
    skills = discover_skills(codex_home)
    selected = set(keep_names or DEFAULT_KEEP_NAMES)
    output = codex_home / f"{profile_name}.config.toml"
    output.write_text(
        render_profile(
            skills,
            selected,
            runtime_command=runtime_command,
            approve_mutations=approve_mutations,
        ),
        encoding="utf-8",
        newline="\n",
    )
    enabled = sum(name in selected for _, name in skills)
    return output, enabled, len(skills) - enabled


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--codex-home", type=Path, required=True)
    parser.add_argument("--profile-name", default="eda-runtime")
    parser.add_argument("--runtime-command", default="eda-runtime")
    parser.add_argument(
        "--approve-mutations",
        action="store_true",
        help=(
            "Pre-approve only typed Runtime mutation tools for a separately authorized "
            "unattended profile."
        ),
    )
    parser.add_argument("--keep-name", action="append", dest="keep_names")
    args = parser.parse_args()
    output, enabled, disabled = install_profile(
        args.codex_home.expanduser().resolve(),
        profile_name=args.profile_name,
        keep_names=set(args.keep_names) if args.keep_names else None,
        runtime_command=args.runtime_command,
        approve_mutations=args.approve_mutations,
    )
    print(
        json.dumps(
            {
                "status": "installed",
                "profile": args.profile_name,
                "path": str(output),
                "enabled_skills": enabled,
                "disabled_skills": disabled,
            },
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
